from controle_produtos3 import *

inventario = []
printLinha()
print('Cadastrando...')
printLinha()
cadastrarProduto(inventario)
printLinha()
print('Exibindo...')
printLinha()
exibirProduto(inventario)
printLinha()
print('Pesquisando...')
printLinha()
buscarProduto(inventario)
printLinha()
print('Descontando...')
printLinha()
porc = int(input('Digite o desconto (%): '))
printLinha()
descontarProduto(inventario, porc)
printLinha()
print('Excluindo...')
printLinha()
print(excluirProduto(inventario))
exibirProduto(inventario)
printLinha()
print('Resumo do inventário: ')
printLinha()
exibirValores(inventario)