from controle_produtos3 import *

inventario = []
print('------------------')
print('Cadastrando...')
print('------------------')
cadastrarProduto(inventario)
print('------------------')
print('Exibindo...')
print('------------------')
exibirProduto(inventario)
print('------------------')
print('Pesquisando...')
print('------------------')
buscarProduto(inventario)
print('------------------')
print('Descontando...')
print('------------------')
porc = int(input('Digite o desconto (%): '))
print('------------------')
descontarProduto(inventario, porc)
print('------------------')
print('Excluindo...')
print('------------------')
print(excluirProduto(inventario))
exibirProduto(inventario)
print('------------------')
print('Resumo do inventário: ')
print('------------------')
exibirValores(inventario)